### ISSUE TITLE
duplicate are shown

### ISSUE THREAD

**Issue by stijnsanders** [scripting/scriptingchat#1]
First my first message was shown multiple times after 'update' (because I had the link wrong at first)
then my next post was shown multiple times.
![image](https://user-images.githubusercontent.com/504770/56977487-92380000-6b75-11e9-9f7b-72bd6d48d8df.png)

**Comment by scripting** [comment]
It's not clear what you did. Can you provide a set of steps to reproduce?

**Comment by stijnsanders** [comment]
It's when I open http://scripting.com/?tab=chat even in a new tab.

**Comment by stijnsanders** [comment]
only now they are getting numbered from idChatMsg0 up 
![image](https://user-images.githubusercontent.com/504770/56978356-92d19600-6b77-11e9-86ad-c2d04ce5d3bf.png)

**Comment by stijnsanders** [comment]
a few pageviews back I got a different time indication on each one, as if the one message is duplicated for each message in your current chat-log... but I guess the first client-side update sets them all to the new display for the duplicated item...

**Comment by stijnsanders** [comment]
Oh, I've posted this item on the repo for the server. I guess the client-source is in the other repo?

**Comment by stijnsanders** [comment]
Look if you currently open http://chat.scripting.com/getchatlog raw, my 'see here' message is repeated there as well.

**Comment by scripting** [comment]
Steps to reproduce? (Second request.)

**Comment by stijnsanders** [comment]
Tried to reproduce. Didn't get new duplicates on this new message, but if you look at the data, id's 42,43 and 52 through 59 are the duplicates, if they're really there, why where they added multiple times? Also I've been searching the source here for "getchatlog" but can't seem to find it, where is it?

**Comment by stijnsanders** [comment]
Whow! console threw a bunch of `serverCall: verb == saveprefs, apiUrl == http://chat.scripting.com/saveprefs?jsontext=` just while I was typing! could that be causing new id's?
